env:
  browser: true

parserOptions:
  ecmaVersion: 2022
  sourceType: module

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended

settings:
  react:
    version: '18'
